#!/bin/bash
set -eu

echo "🚀 Valkey Admin Quickstart"
echo "=========================="
echo ""

# Source common setup functions
source "$(dirname "$0")/scripts/common-setup.sh"

# Run common setup steps
run_common_setup

# Step 4: Create frontend environment file for auto-connection
echo "⚙️  Configuring auto-connection..."
VITE_ENV_FILE="apps/frontend/.env.local"
mkdir -p "$(dirname "$VITE_ENV_FILE")"

cat > "$VITE_ENV_FILE" << EOF
# Auto-generated by quickstart.sh
# Local Valkey cluster connection details
VITE_LOCAL_VALKEY_HOST=$ANNOUNCE_IP
VITE_LOCAL_VALKEY_PORT=7001
VITE_LOCAL_VALKEY_NAME=Local Valkey Cluster
EOF

echo "✅ Auto-connection configured for $ANNOUNCE_IP:7001"
echo ""

# Step 5: Start development servers
echo "🎉 Setup complete! Starting development servers..."
echo "📝 The application will open at http://localhost:5173"
echo "🔌 Auto-connection to local cluster is configured"
echo ""
echo "💡 Cluster is running in the background"
echo "   - Use 'docker logs valkey-cluster-valkey-7001-1' to see cluster logs"
echo "   - Use 'docker compose -f tools/valkey-cluster/docker-compose.yml down -v' to stop cluster"
echo "   - Press Ctrl+C to stop development servers"
echo ""

npm run dev
